### ISSUE TITLE
Does this crawler support crawler the node behind the NAT?

### ISSUE THREAD

**Issue by yourmoonlight** [dennis-tra/nebula#23]
Hi guys, this crawler looks amazing. 
I am curious about how do we crawl the node behind the nat?

**Comment by dennis-tra** [comment]
Hi @yourmoonlight, thanks!

Generally, this crawler **does not** crawl peers behind NATs as they are usually not publicly reachable.

If peers detect that they are behind a NAT device they start operating in DHT-Client mode. However, only DHT-Server nodes end up in routing tables which Nebula uses to recursively enumerate the DHT. So, the current implementation does not allow systematic crawling of DHT-Client nodes.

Please note, if there was a systematic approach to enumerate DHT-Client peers there are NAT hole punching mechanisms. See this recent blog post:

https://blog.ipfs.io/2022-01-20-libp2p-hole-punching/

I hope this has answered your question :)

**Comment by yourmoonlight** [comment]
> 

Oh I see，gracias～
